### PR TITLE
Add a function to return plan file as a dataframe

### PR DESCRIPTION
**Pull request by gabRpt**
Returns dataframes with the following relations between them
Person : None
Plan : person_id
Activity : plan_id
Leg : plan_id
Route :leg_id
The column names of the dataframes are the same as the attribute names (<name:'value'> and <attribute> are parsed)

### CODE REVIEW

**Comment by Nitnelav** [comment]
I'd love to see this merged, any interest in pursuing it of should we just fork the project ?

**Comment by Janekdererste** [comment]
Yes, I do. Everyone who is part of the VSP-Github group. I think @billyc is in charge of this repo.

**Comment by Nitnelav** [comment]
Hi ! any news regarding this issue ?

**Comment by Nitnelav** [comment]
https://github.com/Universite-Gustave-Eiffel/matsim-python

**Comment by rakow** [comment]
Can you update your PR to include the latest changes. I will then merge it soon.

**Comment by Nitnelav** [comment]
Cool ! I think I managed to update everything into a single PR here  : https://github.com/matsim-vsp/matsim-python-tools/pull/20

**Pull request merged**
