### PR TITLE
Added the plan inheritance record inspector

### PR DESCRIPTION
**Pull request by neuma**
Initial release of the Plan Inheritance Record Inspector

The app is built on [Dash/Plotly](https://dash.plotly.com/). It allows to visually inspect the [plan inheritance records of a MATSim run](https://github.com/matsim-org/matsim-libs/pull/2831). Current status is:
- Two tabs with visualizations: The Single Agent Analysis and the Top N Overview.
- Added some patterns for interactions and styling that may facilitate the development of further analyses.
- Largest setup tested featured 640k plan inheritance records - 84k agents with max 4 plans for 160 iterations.

Single Trip Analysis
- Allows to inspects all plans of a single agent
- Choose or type in an agent id
- The table show all the plans of that agent - per default sorted by age
- The left plot links each plan with its ancestor. Each plan is shown once as a single node. The colored nodes represent the the initial plan and the plans of the final choice-set.
- The right plot follows the same lineage but features one node for each selected plan of each iteration. That is, a plan may be drawn more than once, if the plan had been selected in more than one iteration.
- Both plots allow to hover over a node which then highlights the corresponding plan in the table.

image

Top N Overview
- Allows to compare the lineage of the plans of the first n agent.
- For each iteration, the node represents the selected plan.
- Each selected plan is linked to its ancestor.

image

### CODE REVIEW

**Comment by rakow** [comment]
Looks very impressive! I will try it next week and hopefully merge it by then.

**Comment by rakow** [comment]
I have a few requests that hopefully will improve the usability:

- I would propose to move this file to a package named "viz", instead of "planInheritance". We may put other viz related things there if they come up.
- In setup.py under `extras_require` please add a 'viz' entry and define the needed dependencies for this script.
- It would be great if the main method makes use of an ArgumentParser and defines all configurable options.  In this case at least the path to the plan record file, which is hard coded in the script right now.

**Comment by neuma** [comment]
@rakow Thanks for the your feedback.

I am not that familiar with the setuptools and don't know how to test this. From my understanding, pandas can be left out since this comes as a mandatory requirement and is thus installed by default. This reduces the optional dependencies for the viz component to

> 'viz': ["dash", "plotly.express", "dash_cytoscape", "dash_bootstrap_components"]

Or do I miss something?

**Comment by neuma** [comment]
Example data created from a 160 iterations run of the MATSim Sioux Falls Scenario and config switch
```
	<module name="planInheritance" >
		<!-- Specifies whether or not PlanInheritance Information should be tracked. -->
		<param name="enabled" value="true" />
	</module>
```

[planInheritanceRecords.csv.gz](https://github.com/matsim-vsp/matsim-python-tools/files/14492824/planInheritanceRecords.csv.gz)
[planInheritanceRecords_shares.csv](https://github.com/matsim-vsp/matsim-python-tools/files/14492828/planInheritanceRecords_shares.csv)
[planInheritanceRecords_shares_selected.csv](https://github.com/matsim-vsp/matsim-python-tools/files/14492829/planInheritanceRecords_shares_selected.csv)

**Review by rakow — APPROVED** [review]

**Review by rakow — APPROVED** [review]
I added the dependencies to the setup.py and also added an entry point so that a cli script will be generated for it.

**Comment by neuma** [comment]
> I added the dependencies to the setup.py and also added an entry point so that a cli script will be generated for it.

Thanks a lot

**Pull request merged**
